# To boot the app run the following:
# docker-compose run auto-gpt
# NOTE: Version 3.9 requires at least docker-compose version 1.29.0 !
version: "3.9"

services:
  gptfx:
    depends_on:
      - config_container
      - auto-gpt
      - output_container
    build:
      dockerfile: Dockerfile
      context: ../
    volumes:
      - ./:/app/gptfx
    profiles: [
      "exclude-from-up",
    ]

  auto-gpt:
    depends_on:
      - redis
    build:
      dockerfile: ./Dockerfile
      context: ../
    tty: true
    env_file:
      - ../.env
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: ${REDIS_HOST:-redis}
    volumes:
      - ./:/app/auto-gpt

  config_container:
    image: "tensorflow/tfx_base:latest"
    volumes:
      - ./:/app/config
    profiles: [
      "exclude-from-up",
    ]
    command: [
      "python",
      "-m",
      "config_generator.py"
    ]

  output_container:
    image: "tensorflow/tfx_base:latest"
    volumes:
      - ./:/app/output
    profiles: [
      "exclude-from-up",
    ]
    command: [
      "python",
      "-m",
      "output_processing.py"
    ]

  redis:
    image: "redis/redis-stack-server:latest"

  tfx:
    image: "tensorflow/tfx_base:latest"

